<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Registration &middot; SRP-6a &middot; Ruslan Zavackiy</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description"
        content="SRP-6a PHP Implementation Tutorial &middot; http://zavackiy.com/blog/srp-6a-php-implementation/">
  <meta name="author" content="Ruslan Zavackiy">

  <link  href="templates/media/bootstrap/css/bootstrap.css" rel="stylesheet">
  <style type="text/css">
    body {
      padding-top: 40px;
      padding-bottom: 40px;
      background-color: #f5f5f5;
    }

    .form-signin {
      padding: 19px 29px 29px;
      background-color: #fff;
      border: 1px solid #e5e5e5;
      -webkit-border-radius: 5px;
      -moz-border-radius: 5px;
      border-radius: 5px;
      -webkit-box-shadow: 0 1px 2px rgba(0, 0, 0, .05);
      -moz-box-shadow: 0 1px 2px rgba(0, 0, 0, .05);
      box-shadow: 0 1px 2px rgba(0, 0, 0, .05);
    }

    .form-signin .form-signin-heading,
    .form-signin .checkbox {
      margin-bottom: 10px;
    }

    .form-signin input[type="text"],
    .form-signin input[type="password"] {
      font-size: 16px;
      height: auto;
      margin-bottom: 15px;
      padding: 7px 9px;
    }

  </style>
  <link  href="templates/media/bootstrap/css/bootstrap-responsive.css" rel="stylesheet">

  <!--[if lt IE 9]>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->
</head>

<body>

<div class="container">
  <div class="row">
    <div class="offset3 span6">

      <form id="register-form" class="form-signin" method="post">
        <h2 class="form-signin-heading">Registration Form</h2>
        <input name="email" value="ruslan.zavackiy@gmail.com" type="text" class="input-block-level" placeholder="Email address">
        <input id="password" value="random-password" name="password" type="password" class="input-block-level" placeholder="Password">

        <input id="password-salt" type="hidden" name="password_salt">
        <input id="password-verifier" type="hidden" name="password_verifier">

        <button id="registerBtn" name="registerBtn" class="btn btn-large btn-primary" type="submit">Register
        </button>
      </form>

      <div class="alert alert-success">
        <div>
          <b>Password salt</b>
          <div id="password-salt-output" style="overflow: hidden;">&nbsp;</div>
        </div>
        <div>
          <b>Password verifier</b>
          <div id="password-verifier-output" style="overflow: hidden; overflow-x: visible;">&nbsp;</div>
        </div>
        <div id="register-output" style="margin-top: 10px;"></div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="offset3 span6">
      <form id="login-form" action="login.php" class="form-signin" method="post">
        <h2 class="form-signin-heading">Login Form</h2>
        <input id="email-login" value="ruslan.zavackiy@gmail.com" name="email" type="text" class="input-block-level" placeholder="Email address">
        <input id="password-login" value="random-password" name="password" type="password" class="input-block-level" placeholder="Password">

        <button id="loginBtn" name="registerBtn" class="btn btn-large btn-primary" type="submit">Login</button>
      </form>

      <div class="alert alert-info">
        <div id="login-output" style="margin-top: 10px; overflow: hidden; overflow-x: visible;"></div>
      </div>
    </div>
  </div>


</div>

<script src="templates/media/jquery.js"></script>
<script src="templates/media/bootstrap/js/bootstrap.min.js"></script>

<script src="srp/Client/lib/biginteger.js"></script>
<script src="srp/Client/lib/sha256.js"></script>
<script src="srp/Client/lib/isaac.js"></script>
<script src="srp/Client/lib/random.js"></script>
<script src="srp/Client/lib/srp.js"></script>

<script src="srp/Client/register.js"></script>
<script src="srp/Client/login.js"></script>

<script type="text/javascript">
  $(function () {
    Register.initialize({
      formId: '#register-form',
      registerBtnId: '#registerBtn',
      passwordId: '#password',
      passwordSaltId: '#password-salt',
      passwordVerifierId: '#password-verifier'
    });

    Login.initialize({
      emailId: '#email-login',
      formId: '#login-form',
      registerBtnId: '#loginBtn',
      passwordId: '#password-login',
      passwordSaltId: '#password-login-salt',
      passwordVerifierId: '#password-login-verifier',
      url: 'login.php'
    });

    var registerForm = $('#register-form');
    registerForm.on('submit.srp', function () {
      var fields = registerForm.serializeArray();

      var values = {
        registerBtn: true
      };

      $.each(fields, function (i, field) {
        if (field.name === 'password') return;
        values[field.name] = field.value;
      });

      $.post('index.php', values, function (response) {
        if (response.error) {
          $('#register-output').html(response.error);
        } else {
          $('#register-output').html("User registerd with id: " + response['user-id']);
        }
      }, 'json');

      return false;
    });
  });
</script>

</body>
</html>
